"""Schema migrations, for PostgreSQL.

## Why a list of scripts and not a schema file

A schema file tells you what the database looks like now. It does not tell you
how to get an existing one there. So the shape is expressed as an ordered list
of forward steps, each applied exactly once and recorded in
`schema_migrations`. Adding a column means appending a step, never editing one
that has shipped.

Step 1 is the whole schema in one piece, rather than the three SQLite steps
this grew through. Those three described how a single-user SQLite file became a
multi-user one, and no PostgreSQL database has ever been in any of those
intermediate states — replaying that history here would be re-enacting somebody
else's past. The single-user data was cleared rather than migrated, which is
what makes collapsing them honest.

## The five kinds of row

The separation is the whole design, so it is worth stating before the tables.

- **Facts** — `cash_samples`, `source_events`, `xp_events`, and the `matches`
  they hang off. What an agent observed. Immutable once written. Every one
  carries who saw it, which run of that agent saw it, its place in that agent's
  sequence, and three timestamps that are routinely different.
- **Conclusions** — *none of them are here.* Lives, kits, ledger entries,
  break-even times and classifications are computed from facts on read by a
  versioned ruleset. Nothing derived is stored, so nothing derived can go
  stale, and a rule change re-reads history instead of migrating it. The one
  apparent exception, `derived_matches`, is a cache that records its own inputs
  and may be deleted at any time.
- **Corrections** — `overrides`. What a person said when a derivation was
  wrong. Kept apart from both of the above, because a correction is neither an
  observation nor a conclusion, and folding it into either loses the ability to
  recompute one without discarding the other.
- **The published log** — `api_events`. Committed deltas in commit order,
  written in the same transaction as the fact they announce. Its `seq` is the
  cursor a browser reconnects on.
- **People** — `users`, `sessions`, `agent_credentials`, `link_codes`. Who is
  allowed to see any of it.

## Why matches are here at all, when segmentation is a conclusion

A match is a conclusion — the server decides where one starts by watching
`game_state`, and the thresholds that decide it are versioned like any other
rule. But it is a conclusion every other fact needs to *point at*, and a
foreign key is worth more than the purity: without it, every read of one match
would scan the whole sample table by timestamp.

The compromise is that `matches` is rebuildable. It holds nothing but identity
and the observations that opened and closed it; drop the table, replay the
`source_events`, and the same matches come back. `segmentation.py` is the only
thing that writes it.

## Timestamps are text

ISO-8601 UTC strings, not `timestamptz`. They are produced in one place
(`utc_now`), always at one precision, so they sort as text exactly as they sort
as instants — and every ruleset already parses them from text. See the note in
`database.py` for why that was not worth changing.
"""

from __future__ import annotations

from datetime import datetime, timezone

import psycopg

MIGRATIONS: list[tuple[int, str]] = [
    (
        1,
        """
        -- ------------------------------------------------------------------
        -- People
        -- ------------------------------------------------------------------
        --
        -- Identity is Google's. `google_sub` is the subject claim, which is
        -- the only stable identifier Google promises: an address can be
        -- reassigned within a workspace, the subject cannot. `email` sits
        -- beside it for the allowlist, never as the key.
        CREATE TABLE users (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            google_sub    TEXT UNIQUE,
            email         TEXT   NOT NULL UNIQUE,
            name          TEXT,
            picture       TEXT,
            created_at    TEXT   NOT NULL,
            last_login_at TEXT
        );

        -- Browser sessions. Server-side rather than a signed cookie, so that
        -- signing out actually ends the session instead of waiting for an
        -- expiry that cannot be recalled. The cookie carries a random token;
        -- only its SHA-256 is stored, so a leaked database yields no usable
        -- cookies.
        CREATE TABLE sessions (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id      BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
            token_hash   TEXT   NOT NULL UNIQUE,
            created_at   TEXT   NOT NULL,
            expires_at   TEXT   NOT NULL,
            last_seen_at TEXT,
            user_agent   TEXT
        );
        CREATE INDEX sessions_user    ON sessions (user_id);
        CREATE INDEX sessions_expires ON sessions (expires_at);

        -- ------------------------------------------------------------------
        -- Who is reporting
        -- ------------------------------------------------------------------

        CREATE TABLE agents (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            agent_id      TEXT   NOT NULL UNIQUE,
            label         TEXT,
            first_seen_at TEXT   NOT NULL,
            last_seen_at  TEXT   NOT NULL,
            last_boot_id  TEXT,
            -- Highest agent_seq held with no gap behind it. This is the number
            -- returned to the agent, and the only thing that licenses it to
            -- forget anything.
            acked_through BIGINT NOT NULL DEFAULT 0,
            user_id       BIGINT REFERENCES users (id) ON DELETE CASCADE
        );
        CREATE INDEX agents_user ON agents (user_id);

        -- One row per run of an agent process. A gap in agent_seq with a boot
        -- change across it is a restart; a gap without one is lost data, and
        -- the difference is worth being able to see.
        CREATE TABLE agent_boots (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            agent_ref     BIGINT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
            boot_id       TEXT   NOT NULL,
            first_seen_at TEXT   NOT NULL,
            last_seen_at  TEXT   NOT NULL,
            UNIQUE (agent_ref, boot_id)
        );

        -- What a linked PC uploads with. Upload-only by construction: nothing
        -- reads these rows to answer a question about data, only to decide
        -- whether a batch may be written and whose it is. Hashed, and revoked
        -- by setting `revoked_at`, which is checked on every request rather
        -- than only at issue.
        CREATE TABLE agent_credentials (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id      BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
            agent_ref    BIGINT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
            token_hash   TEXT   NOT NULL UNIQUE,
            label        TEXT,
            created_at   TEXT   NOT NULL,
            last_used_at TEXT,
            revoked_at   TEXT
        );
        CREATE INDEX agent_credentials_user  ON agent_credentials (user_id);
        CREATE INDEX agent_credentials_agent ON agent_credentials (agent_ref);

        -- The linking handshake. A generic EXE has no idea whose PC it is on,
        -- so it asks for one of these, sends the person to a browser, and
        -- waits. `code` is what a human reads and approves;
        -- `device_secret_hash` proves the *asking* PC is the one collecting
        -- the credential, so reading a code over somebody's shoulder is not
        -- enough to poll for the token first.
        CREATE TABLE link_codes (
            id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code               TEXT   NOT NULL UNIQUE,
            device_secret_hash TEXT   NOT NULL,
            agent_id           TEXT   NOT NULL,
            label              TEXT,
            user_id            BIGINT REFERENCES users (id) ON DELETE CASCADE,
            created_at         TEXT   NOT NULL,
            expires_at         TEXT   NOT NULL,
            approved_at        TEXT,
            consumed_at        TEXT
        );
        CREATE INDEX link_codes_expires ON link_codes (expires_at);

        -- The idempotency gate. Every envelope the server has ever accepted,
        -- by (agent, sequence). One envelope can fan out into several rows --
        -- an xp reading becomes one row per role -- so uniqueness lives here
        -- rather than on the typed tables, where it could not express that.
        CREATE TABLE ingested_envelopes (
            agent_ref BIGINT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
            agent_seq BIGINT NOT NULL,
            kind      TEXT   NOT NULL,
            PRIMARY KEY (agent_ref, agent_seq)
        );

        -- ------------------------------------------------------------------
        -- Facts
        -- ------------------------------------------------------------------

        -- One server session, cut out of the observation stream. See the note
        -- above on why a conclusion is allowed a table.
        CREATE TABLE matches (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            -- Stable natural key, independent of any filename. Everything
            -- outward-facing names a match by this.
            match_key   TEXT   NOT NULL UNIQUE,
            agent_ref   BIGINT REFERENCES agents (id) ON DELETE SET NULL,
            started_at  TEXT   NOT NULL,
            ended_at    TEXT,               -- null while the match is live
            map         TEXT,
            faction     TEXT,
            build       TEXT,
            source      TEXT   NOT NULL,    -- 'agent' | 'import:csv'
            observed_at TEXT   NOT NULL,
            received_at TEXT   NOT NULL,
            ingested_at TEXT   NOT NULL,
            closed      INTEGER NOT NULL DEFAULT 0,
            user_id     BIGINT REFERENCES users (id) ON DELETE CASCADE
        );
        CREATE INDEX matches_started_at ON matches (started_at);
        CREATE INDEX matches_map        ON matches (map);
        CREATE INDEX matches_build      ON matches (build);
        CREATE INDEX matches_open       ON matches (closed, started_at);
        CREATE INDEX matches_agent      ON matches (agent_ref, started_at);
        CREATE INDEX matches_user       ON matches (user_id, started_at);

        -- The profit/loss curve, exactly as the game reported it.
        CREATE TABLE cash_samples (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            match_id    BIGINT NOT NULL REFERENCES matches (id) ON DELETE CASCADE,
            elapsed_sec DOUBLE PRECISION NOT NULL,
            cash        INTEGER NOT NULL,
            life        INTEGER NOT NULL,
            -- The verbatim string Wardogs published, beside the number we read
            -- out of it. This is what makes a wrong parser fixable: re-read
            -- history rather than discover the evidence was thrown away. It
            -- lives here rather than in a second `source_events` row per poll
            -- because a duplicate row per reading doubled the database for one
            -- short string.
            raw         TEXT,
            agent_ref   BIGINT REFERENCES agents (id) ON DELETE SET NULL,
            boot_ref    BIGINT REFERENCES agent_boots (id) ON DELETE SET NULL,
            agent_seq   BIGINT,
            source_ts   TEXT,
            observed_at TEXT   NOT NULL,
            received_at TEXT   NOT NULL,
            ingested_at TEXT   NOT NULL,
            build       TEXT,
            -- Two readings of one match at the same offset are the same
            -- reading. Belt to the envelope gate's braces: it also protects
            -- against a re-import, where the facts arrive with no agent
            -- sequence at all.
            UNIQUE (match_id, elapsed_sec)
        );
        CREATE INDEX cash_samples_match ON cash_samples (match_id, elapsed_sec);

        -- Everything an agent saw that is not an ordinary reading of the
        -- curve: spawns, map loads, agent lifecycle, and any presence poll
        -- where something other than the money changed -- a state transition,
        -- a faction assignment, a value that would not parse. Ordinary playing
        -- polls are `cash_samples` rows, which carry their own raw string, so
        -- nothing observed is missing from the database.
        CREATE TABLE source_events (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            match_id    BIGINT REFERENCES matches (id) ON DELETE CASCADE,
            kind        TEXT   NOT NULL,   -- 'presence'|'spawn'|'map'|'agent_status'
            source      TEXT   NOT NULL,   -- 'rich_presence'|'breadcrumbs'|'agent'
            -- The original factual values, verbatim, as JSON.
            payload     TEXT   NOT NULL,
            life        INTEGER,
            agent_ref   BIGINT REFERENCES agents (id) ON DELETE SET NULL,
            boot_ref    BIGINT REFERENCES agent_boots (id) ON DELETE SET NULL,
            agent_seq   BIGINT,
            source_ts   TEXT,
            observed_at TEXT   NOT NULL,
            received_at TEXT   NOT NULL,
            ingested_at TEXT   NOT NULL,
            build       TEXT
        );
        CREATE INDEX source_events_match ON source_events (match_id, observed_at);
        CREATE INDEX source_events_kind  ON source_events (kind, observed_at);
        CREATE INDEX source_events_seq   ON source_events (agent_ref, agent_seq);

        -- Role XP. The fact is the absolute total the save file held; `delta`
        -- beside it is a convenience computed at ingest from the previous
        -- reading, and is reproducible from the totals alone. The domain layer
        -- reads the totals, never the deltas, so a wrong delta cannot reach a
        -- conclusion.
        CREATE TABLE xp_events (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            match_id    BIGINT REFERENCES matches (id) ON DELETE SET NULL,
            role        TEXT   NOT NULL,
            -- The absolute value the save file held. Null only for history
            -- imported from the CSV-era `role_xp_log.csv`, which recorded
            -- gains and never totals -- a real absence, not a zero, and the
            -- domain falls back to `delta` for exactly those rows.
            total       BIGINT,
            delta       BIGINT,
            agent_ref   BIGINT REFERENCES agents (id) ON DELETE SET NULL,
            boot_ref    BIGINT REFERENCES agent_boots (id) ON DELETE SET NULL,
            agent_seq   BIGINT,
            source_ts   TEXT,
            observed_at TEXT   NOT NULL,
            received_at TEXT   NOT NULL,
            ingested_at TEXT   NOT NULL,
            build       TEXT,
            CHECK (total IS NOT NULL OR delta IS NOT NULL)
        );
        CREATE INDEX xp_events_match ON xp_events (match_id);
        CREATE INDEX xp_events_time  ON xp_events (observed_at);
        CREATE INDEX xp_events_role  ON xp_events (role, observed_at);

        -- ------------------------------------------------------------------
        -- Corrections
        -- ------------------------------------------------------------------

        CREATE TABLE overrides (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            scope       TEXT   NOT NULL,   -- 'life_kit_cost'
            match_id    BIGINT NOT NULL REFERENCES matches (id) ON DELETE CASCADE,
            life_number INTEGER NOT NULL,
            value       DOUBLE PRECISION,  -- null clears it
            note        TEXT,
            created_at  TEXT   NOT NULL,
            UNIQUE (scope, match_id, life_number)
        );

        -- ------------------------------------------------------------------
        -- The published log
        -- ------------------------------------------------------------------

        CREATE TABLE api_events (
            seq          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kind         TEXT NOT NULL,
            match_key    TEXT,
            payload      TEXT NOT NULL,
            committed_at TEXT NOT NULL,
            user_id      BIGINT
        );
        CREATE INDEX api_events_match ON api_events (match_key, seq);
        CREATE INDEX api_events_user  ON api_events (user_id, seq);

        -- ------------------------------------------------------------------
        -- The derived cache
        -- ------------------------------------------------------------------
        --
        -- Added because a measurement said so, not because it seemed wise.
        -- `profitdog_server.bench` over a thousand hours of play (1,351
        -- matches, 7,429 lives, 1.34M readings) put a full re-derivation of
        -- every match at 3.2 seconds, which is the cost of loading the history
        -- page. One match on its own derives in about 2ms, so the cost is
        -- entirely in the count.
        --
        -- Nothing here is a source of truth. Every row is reproducible from
        -- facts, every row records the exact inputs it was built from, and
        -- `DELETE FROM derived_matches` is a supported operation that costs
        -- one slow page load. `tests/test_cache.py` asserts that dropping it
        -- changes no answer anywhere.
        CREATE TABLE derived_matches (
            match_id    BIGINT PRIMARY KEY REFERENCES matches (id) ON DELETE CASCADE,
            -- Which rules produced this, and a fingerprint of their source.
            -- The version alone is not enough: editing `v1.py` without
            -- renaming it would otherwise leave every cached row silently
            -- stale.
            ruleset     TEXT NOT NULL,
            fingerprint TEXT NOT NULL,
            -- Identifies the facts and corrections this was built from. Any
            -- change to either produces a different value and a rebuild.
            input_hash  TEXT NOT NULL,
            payload     TEXT NOT NULL,
            built_at    TEXT NOT NULL
        );
        """,
    ),
    (
        2,
        """
        -- Which build of the agent last reported from this PC.
        --
        -- Reporting only. Nothing derives from it and nothing may: an agent
        -- old enough not to send one leaves it NULL, and a NULL here has to
        -- keep meaning "it did not say", not "it is out of date".
        ALTER TABLE agents ADD COLUMN agent_version TEXT;
        """,
    ),
]


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="microseconds")


def current_version(conn: psycopg.Connection) -> int:
    conn.execute(
        "CREATE TABLE IF NOT EXISTS schema_migrations ("
        " version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)"
    )
    row = conn.execute("SELECT MAX(version) FROM schema_migrations").fetchone()
    return (row[0] if row else 0) or 0


def migrate(conn: psycopg.Connection) -> int:
    """Bring a database up to the latest schema. Returns the version reached.

    Each step is committed on its own, so an interrupted migration leaves the
    database at the last version that fully applied rather than somewhere
    between two. PostgreSQL runs DDL inside transactions, so "fully applied"
    means exactly that — unlike the engine this grew up on, a half-run step is
    not a state that can exist.
    """
    version = current_version(conn)
    for number, script in MIGRATIONS:
        if number <= version:
            continue
        conn.execute(script)
        conn.execute(
            "INSERT INTO schema_migrations (version, applied_at) VALUES (%s, %s)",
            (number, _now()),
        )
        conn.commit()
        version = number
    return version


LATEST_VERSION = MIGRATIONS[-1][0]

__all__ = ["MIGRATIONS", "LATEST_VERSION", "current_version", "migrate"]
